### ISSUE TITLE
about code font

### ISSUE THREAD

**Issue by learning310** [ujwaljain/typora-theme-gallery#2]
I'm very excited when i see your theme in Typora.To be honest,i can't code css.So, i want ask you a question about the code font. I like consolas font.So can you tell how to do this.I'm very appreciated.

**Comment by ujwaljain** [comment]
Open css file in a text editor and add "Consolas" in font-family.  For example: 
font-family: Consolas, "Open Sans", "Clear Sans", sans-serif;
