### ISSUE TITLE
mistake of download link

### ISSUE THREAD

**Issue by kelzr** [ujwaljain/typora-theme-gallery#3]
The [download link](https://raw.githubusercontent.com/ujwaljain/typora-theme-gallery/gh-pages/media/theme/barfi/barfi.css) that you put in [this page](http://theme.typora.io/theme/Barfi/) is wrong. Please updates the link. 

ps. I think your theme is the best dark theme shown in the Typora's theme gallery.

**Comment by Atcold** [comment]
Yeahm @ujwaljain, can you please provide the theme download package?
You can add it to a release, here on GitHub.

**Comment by ujwaljain** [comment]
Fixed it.
