### ISSUE TITLE
Icons are misplaced when export PDF

### ISSUE THREAD

**Issue by AdelsJarlen** [ujwaljain/typora-theme-gallery#4]
![image](https://user-images.githubusercontent.com/94843506/162159251-4a36e062-f0e7-4732-adba-53c7a63ef2b7.png)

**Comment by ujwaljain** [comment]
Looks like there is no way to fix this issue. If you generate html, it gets exported correctly to html however html to pdf still gets messed up. If I have to guess this is inherent to how html to pdf conversion is done.

I have removed the icons when exported to pdf.

**Comment by ujwaljain** [comment]
[sneh.zip](https://github.com/ujwaljain/typora-theme-gallery/files/8479018/sneh.zip)

Can you try this release and see if its better?

**Comment by AdelsJarlen** [comment]
![image](https://user-images.githubusercontent.com/94843506/164071196-838b8695-c6f0-4f35-ba71-8e577daf3ce8.png)

The new release removed the icons entirely when exporting to a PDF.

**Comment by ujwaljain** [comment]
Yes, there is no way to fix problem as issue is in pdf generation code which neither I or Typora controls.

**Comment by AdelsJarlen** [comment]
That's a shame, but thanks for trying to solve the issue :) Love your Typora theme. I found a workaround that somewhat solves the issue. I first export as HTML, then I create a PDF in my browser.
