### ISSUE TITLE
h4~h6 not show

### ISSUE THREAD

**Issue by likfe** [ujwaljain/typora-theme-gallery#5]
Your theme is very nice. When I use it,I find an issue:

below is my source content:
```
# 一级标题[一级标题]( http://abc.com)

## 二级标题[二级标题]( http://abc.com)

### 三级标题[三级标题]( http://abc.com)

#### 四级标题[四级标题]( http://abc.com) 

##### 五级标题[五级标题]( http://abc.com)

###### 六级标题[六级标题]( http://abc.com)

# xxxxxx
```

They show as :
![image](https://user-images.githubusercontent.com/7094014/175007909-b7a2968c-f2ff-42ad-8aa4-54b552329a22.png)

The H4~H6 dismiss

**Comment by ujwaljain** [comment]
Yes, H4 to H6 won't work. See https://theme.typora.io/theme/Sneh/. Assumption is that people won't use H4-H6 headers. I can create another them without support for callout boxes.

Use following to get callout boxes.

```
#### header 4
> quote

##### header 5
> quote 2

###### header 6
> quote 3 
```
